---
functional:
  - Решение задачи на скорость против другого игрока. Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
  - Каждый игрок видит код своего соперника в режиме он-лайн
  - Каждый игрок имеет кнопку "check" для проверки своего решения. Попыток проверки неограниченно
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть. Первый в любой момент игры, пока она не закончена, может переподключиться в игру
  - В игру можно играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Пользователь находится в режиме ожидания второго игрока
  - Можно выбрать игру по уровню сложности
  - Игра высвечивается как "доступная для подключения" у других пользователей
  - Второй пользователь нажимает "connect to game" и обоих перебрасывает в игру
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры
  - Победитель-игрок может выйти из игры по нажатию кнопки "exit", которая у него появилась. Кнопка "check" у него более неактивна, но он может остаться и посмотреть ещё раз на свой код
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователи-игроки не могут редактировать код друг-друга
  - Пользователи, вошедшие в игру в качестве зрителя, не имеют доступа к редактированию кода
  - Пользователи не могут создавать одновременно две игры
