---
functional:
  - Пользователь может выбрать один из предложенных языков программирования
  - Пользователь может самостоятельно создать игру
  - Пользователь может делиться ссылкой на игру
  - Пользователи могут выбрать с кем играть (с другим пользователем, другом или ботом)
  - Пользователь может присоединиться к игре в качестве игрока
  - Пользователь может присоединиться к игре в качестве зрителя
  - Пользователь может выбрать уровень сложности игры
  - Пользователи могут установить время, за которое необходимо справится с заданием
  - Пользователи могут выбрать задание
  - Пользователи могут писать в чат игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователи, вошедшие в игру в качестве зрителя, не имеют доступа к редактированию кода
